namespace Linkplay.HttpApi.Model;

public record DeviceStatus
{
    public string? Uuid { get; init; }
    public string? DeviceName { get; init; }
    public string? GroupName { get; init; }
    public string? Ssid { get; init; }
    public string? Language { get; init; }
    public string? Firmware { get; init; }
    public string? Hardware { get; init; }
    public string? Build { get; init; }
    public string? Project { get; init; }
    public string? PrivPrj { get; init; }
    public string? ProjectBuildName { get; init; }
    public string? Release { get; init; }
    public string? TempUuid { get; init; }
    public bool HideSSID { get; init; }
    public string? SSIDStrategy { get; init; }
    public string? Branch { get; init; }
    public int Group { get; init; }
    public string? WmrmVersion { get; init; }
    public bool Internet { get; init; }
    public string? MAC { get; init; }
    public string? STAMAC { get; init; }
    public string? CountryCode { get; init; }
    public string? CountryRegion { get; init; }
    public int Netstat { get; init; }
    public HexedString Essid { get; init; }
    public string? Apcli0 { get; init; }
    public string? Eth2 { get; init; }
    public string? Ra0 { get; init; }
    public bool EthDhcp { get; init; }
    public string? EthStaticIp { get; init; }
    public string? EthStaticMask { get; init; }
    public string? EthStaticGateway { get; init; }
    public string? EthStaticDns1 { get; init; }
    public string? EthStaticDns2 { get; init; }
    public bool VersionUpdate { get; init; }
    public string? NewVer { get; init; }
    public string? McuVer { get; init; }
    public string? McuVerNew { get; init; }
    public string? DspVer { get; init; }
    public string? DspVerNew { get; init; }
    public string? Date { get; init; }
    public string? Time { get; init; }
    public string? Tz { get; init; }
    public string? DstEnable { get; init; }
    public string? Region { get; init; }
    public bool PromptStatus { get; init; }
    public string? IotVer { get; init; }
    public string? UpnpVersion { get; init; }
    public string? Cap1 { get; init; }
    public string? Capability { get; init; }
    public string? Languages { get; init; }
    public string? StreamsAll { get; init; }
    public string? Streams { get; init; }
    public string? External { get; init; }
    public string? PlmSupport { get; init; }
    public string? PreinitKey { get; init; }
    public bool SpotifyActive { get; init; }
    public string? LbcSupport { get; init; }
    public string? PrivacyMode { get; init; }
    public string? WifiChannel { get; init; }
    public string? RSSI { get; init; }
    public string? BSSID { get; init; }
    public bool Battery { get; init; }
    public string? BatteryPercent { get; init; }
    public string? Securemode { get; init; }
    public string? Auth { get; init; }
    public string? Encry { get; init; }
    public string? UpnpUuid { get; init; }
    public string? UartPassPort { get; init; }
    public string? CommunicationPort { get; init; }
    public string? WebFirmwareUpdateHide { get; init; }
    public string? IgnoreTalkstart { get; init; }
    public string? WebLoginResult { get; init; }
    public string? SilenceOTATime { get; init; }
    public string? IgnoreSilenceOTATime { get; init; }
    public string? NewTuneinPreinitAndAlarm { get; init; }
    public string? IheartradioNew { get; init; }
    public string? NewIheartPodcast { get; init; }
    public string? TidalVersion { get; init; }
    public string? ServiceVersion { get; init; }
    public string? Security { get; init; }
    public string? SecurityVersion { get; init; }
}

